### ISSUE TITLE
Only Ops are able to use ability

### ISSUE THREAD

**Issue by Swizzler121** [nylser/TreeDestroyage#11]
MC 1.12.2
Forge 1.12.2 - 14.23.4.2705
Sponge 1.12.2-2705-7.1.0-BETA-3206

Only Opped users are able to activate tree destroyage when they hit it with axes (currently all axes have the ability on our server.) 

unopped players break the tree same as vanilla, one block at a time.

There's no debug mode provided in the config so I'm unable to provide info beyond this.

**Comment by axle2005** [comment]
Players need to be given the permission: treedestroyage.destroy
If using LuckPerms, 
```
lp user <username> permmission set treedestroyage.destroy true
```
