### ISSUE TITLE
Could not pass ChangeBlockEvent$Break$Impl to Plugin{id=treedestroyage 

### ISSUE THREAD

**Issue by ziceptor** [nylser/TreeDestroyage#4]
https://gist.github.com/ziceptor/37d7e178834aa5c98ec67f37e4a696fc

forge-1.11.2-13.20.0.2227-universal.jar
spongeforge-1.11.2-2227-6.0.0-BETA-2260.jar
TreeDestroyage-0.11-DEV-API5.0.0-0-all.jar

**Comment by nylser** [comment]
Fixed with update to newest API
